/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calc.newpackage;

import javax.swing.JOptionPane;
import org.nfunk.jep.JEP;

/**
 *
 * @author mathe
 */
public class NewJFrame extends javax.swing.JFrame {

    boolean newton, secante, bisseccao, pontofixo, hibrido, raiz = false;
    
    public static double f(double y, String function){
    JEP j = new JEP();
    j.addStandardConstants();
    j.addStandardFunctions();
    j.addVariable("x", y);
    j.parseExpression(function);
    return j.getValue();
    }
    
    public static double df(double y, String dfunction){
    JEP j = new JEP();
    j.addStandardConstants();
    j.addStandardFunctions();
    j.addVariable("x", y);
    j.parseExpression(dfunction);
    return j.getValue();
    }
    
    public static double phi(double y, String phi){
    JEP j = new JEP();
    j.addStandardConstants();
    j.addStandardFunctions();
    j.addVariable("x", y);
    j.parseExpression(phi);
    return j.getValue();
    }
    
    public static double newton(double x, double e,String function, String dfunction){

// Declara variáveis
int n = 0;
boolean p = true;

// Loop de teste
do{
if(Math.abs(f(x - (f(x, function)/df(x, dfunction)), function))<e) p = false; // Verifica se x é menor que o erro
x = x - (f(x, function)/df(x, dfunction)); // altera o valor de x
n++;
if(n>20) p = false; // Sai do loop caso n seja maior que 20
}while(p);

return x; 
}
    
    public static double secante(double a, double b, double e, String function){

// Declara variáveis
double x; 
int n = 0;
boolean p = true;


// Loop de teste
do{
x = (a*f(b, function)-b*f(a, function))/(f(b, function)-f(a, function)); // altera valor de X
if(Math.abs(x-b)<e) p = false;  // Verifica se x é menor que o erro
a = b; // altera a
b = x; // altera b
n++;
if(n>20) p = false; // Sai do loop caso n seja maior que 20
}while(p);

return x; 
}
   
    public static double bissecção(double a, double b, double e, String function){
       // Declara variáveis
double x;
int n = 0;
boolean p = true, fail = false; 
 

// Loop de teste
do{
x = (a+b)/2; // Faz a media de a e b
if((b-a)/2 < e) p = false; // Verifica se x é menor que o erro
if((f(a, function)*f(x, function)>0)) a = x; // Altera valor de a
if((f(b, function)*f(x, function)>0)) b = x; // Altera valor de b
// Verifica se o método da bissecção falhou
else if(f(a, function)*f(x, function)>0 && f(x, function)*f(b, function)>0) {p = false; 
fail = true; 
}
n++; 
if(n>20) p = false; // Sai do loop caso n seja maior que 20
}while(p==true); 

return x; 
   }
    
    public static double ponto(double x,double erro, String phi){

int n = 0;
boolean p = true;


// Loop de teste
do{
if(Math.abs(phi(x, phi) - x)<erro) p = false; 
x = phi(x, phi); // altera valor de X
n++;
if(n>20) p = false; // Sai do loop caso n seja maior que 20
}while(p);

return x;    
    }
    
    private void raiz(String function){
    cxo.setEnabled(true);
    cxo.setEditable(false);
    cx1.setEnabled(true);
    cx1.setEditable(false); 
    long i; 
    for(i=-100000;i<=100000;i++){
        if((f(i, function)*f(i+1, function))<0){
          cxo.setText(String.valueOf(i));
          cx1.setText(String.valueOf(i+1));
          i = 100000;
        }
    }
    }
    
 
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cfuncao = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cderivada = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cxo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cx1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cerro = new javax.swing.JTextField();
        bsecante = new javax.swing.JButton();
        bnewton = new javax.swing.JButton();
        bbisseccao = new javax.swing.JButton();
        bpontofixo = new javax.swing.JButton();
        bajuda = new javax.swing.JButton();
        bisolaraiz = new javax.swing.JButton();
        bcalcular = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        craiz = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cálculo de Raiz - UTFPR");

        jLabel1.setText("Função");

        cfuncao.setEnabled(false);

        jLabel7.setText("Derivada/Phi");

        cderivada.setEnabled(false);

        jLabel8.setText("A/X0");

        cxo.setEnabled(false);

        jLabel9.setText("B/X1");

        cx1.setEnabled(false);

        jLabel10.setText("Erro");

        cerro.setEnabled(false);

        bsecante.setText("Secante");
        bsecante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsecanteActionPerformed(evt);
            }
        });

        bnewton.setText("Newton");
        bnewton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnewtonActionPerformed(evt);
            }
        });

        bbisseccao.setText("Bissecção");
        bbisseccao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbisseccaoActionPerformed(evt);
            }
        });

        bpontofixo.setText("Ponto Fixo");
        bpontofixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpontofixoActionPerformed(evt);
            }
        });

        bajuda.setText("Sobre");
        bajuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajudaActionPerformed(evt);
            }
        });

        bisolaraiz.setText("Isolar Raiz");
        bisolaraiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bisolaraizActionPerformed(evt);
            }
        });

        bcalcular.setText("FAZER O CÁLCULO");
        bcalcular.setEnabled(false);
        bcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcalcularActionPerformed(evt);
            }
        });

        jLabel11.setText("Raiz calculada");

        craiz.setEnabled(false);

        jLabel2.setText("CÁLCULO DE RAIZES - UTFPR - CÁLCULO NUMÉRICO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(cfuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cderivada, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cx1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(craiz, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cerro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(bajuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bnewton, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bisolaraiz, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(bsecante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bbisseccao, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bpontofixo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(bcalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(3, 3, 3)
                        .addComponent(cxo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3)
                        .addComponent(cfuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cderivada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cerro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(craiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsecante)
                    .addComponent(bbisseccao)
                    .addComponent(bnewton)
                    .addComponent(bpontofixo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bajuda)
                    .addComponent(bisolaraiz)
                    .addComponent(bcalcular))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bsecanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsecanteActionPerformed
  
        cfuncao.setEnabled(true);
        craiz.setEnabled(false);
        craiz.setText("");
        cerro.setEnabled(true);
        cxo.setEnabled(true);
        cx1.setEnabled(true);
        bnewton.setEnabled(false);
        bpontofixo.setEnabled(false);
        bbisseccao.setEnabled(false);
        bisolaraiz.setEnabled(false);
        bcalcular.setEnabled(true);
        secante = true; 
    }//GEN-LAST:event_bsecanteActionPerformed

    private void bnewtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnewtonActionPerformed
      
        cfuncao.setEnabled(true);
        craiz.setEnabled(false);
        craiz.setText("");
        cderivada.setEnabled(true);
        cerro.setEnabled(true);
        cxo.setEnabled(true);
        bsecante.setEnabled(false);
        bpontofixo.setEnabled(false);
        bbisseccao.setEnabled(false);
        bisolaraiz.setEnabled(false);
        bcalcular.setEnabled(true);
        newton = true; 
    }//GEN-LAST:event_bnewtonActionPerformed

    private void bbisseccaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbisseccaoActionPerformed
       
        cfuncao.setEnabled(true);
        craiz.setEnabled(false);
        craiz.setText("");
        cerro.setEnabled(true);
        cxo.setEnabled(true);
        cx1.setEnabled(true);
        bnewton.setEnabled(false);
        bpontofixo.setEnabled(false);
        bsecante.setEnabled(false);
        bisolaraiz.setEnabled(false);
        bcalcular.setEnabled(true);
        bisseccao = true; 
    }//GEN-LAST:event_bbisseccaoActionPerformed

    private void bpontofixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpontofixoActionPerformed
        
        cfuncao.setEnabled(true);
        craiz.setEnabled(false);
        craiz.setText("");
        cderivada.setEnabled(true);
        cerro.setEnabled(true);
        cxo.setEnabled(true);
        bnewton.setEnabled(false);
        bbisseccao.setEnabled(false);
        bsecante.setEnabled(false);
        bisolaraiz.setEnabled(false);
        bcalcular.setEnabled(true);
        pontofixo = true; 
    }//GEN-LAST:event_bpontofixoActionPerformed

    private void bajudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajudaActionPerformed
       JOptionPane.showMessageDialog(this, "Programa desenvolvido por Matheus Antony\nErros favor reportar\nContato: matheuse@alunos.utfpr.edu.br");
    }//GEN-LAST:event_bajudaActionPerformed

    private void bisolaraizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bisolaraizActionPerformed

        cfuncao.setEnabled(true);
        craiz.setEnabled(false);
        craiz.setText("");
        bnewton.setEnabled(false);
        bpontofixo.setEnabled(false);
        bsecante.setEnabled(false);
        bbisseccao.setEnabled(false);
        bcalcular.setEnabled(true);
        raiz = true; 
    }//GEN-LAST:event_bisolaraizActionPerformed

    private void bcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcalcularActionPerformed
        String sxo, serro, sx1; 
        double xo, erro, x1;
        if(raiz==false){
        craiz.setEnabled(true); 
        craiz.setEditable(false);}
        if(newton) {
            sxo = cxo.getText(); 
            serro = cerro.getText(); 
            xo = Double.parseDouble(sxo);
            erro = Double.parseDouble(serro);
            craiz.setText(String.valueOf(newton(xo,erro,cfuncao.getText(),cderivada.getText())));
        }
        else if(secante) {
            sxo = cxo.getText(); 
            sx1 = cx1.getText();
            serro = cerro.getText(); 
            xo = Double.parseDouble(sxo);
            x1 = Double.parseDouble(sx1); 
            erro = Double.parseDouble(serro);
            craiz.setText(String.valueOf(secante(xo,x1,erro,cfuncao.getText())));
        }
        else if(bisseccao) {
            sxo = cxo.getText(); 
            sx1 = cx1.getText();
            serro = cerro.getText(); 
            xo = Double.parseDouble(sxo);
            x1 = Double.parseDouble(sx1); 
            erro = Double.parseDouble(serro);
            craiz.setText(String.valueOf(bissecção(xo,x1,erro,cfuncao.getText())));
        }else if(pontofixo){
            sxo = cxo.getText();
            serro = cerro.getText();
            xo = Double.parseDouble(sxo);
            erro = Double.parseDouble(serro);
            craiz.setText(String.valueOf(ponto(xo,erro,cderivada.getText())));
        }else if(raiz){
            raiz(cfuncao.getText());            
        }
        
        cfuncao.setEnabled(false);
        cfuncao.setText("");
        cderivada.setEnabled(false);
        cderivada.setText("");
        cerro.setEnabled(false);
        cerro.setText("");
        if(raiz==false){
        cxo.setEnabled(false);
        cxo.setText("");
        cx1.setEnabled(false);
        cx1.setText("");}
        bnewton.setEnabled(true);
        bpontofixo.setEnabled(true);
        bbisseccao.setEnabled(true);
        bsecante.setEnabled(true);
        bisolaraiz.setEnabled(true);
        bcalcular.setEnabled(false);
        
        newton = false;
        secante = false;
        bisseccao = false;
        pontofixo = false;
        hibrido = false;
        raiz = false; 
    }//GEN-LAST:event_bcalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bajuda;
    private javax.swing.JButton bbisseccao;
    private javax.swing.JButton bcalcular;
    private javax.swing.JButton bisolaraiz;
    private javax.swing.JButton bnewton;
    private javax.swing.JButton bpontofixo;
    private javax.swing.JButton bsecante;
    private javax.swing.JTextField cderivada;
    private javax.swing.JTextField cerro;
    private javax.swing.JTextField cfuncao;
    private javax.swing.JTextField craiz;
    private javax.swing.JTextField cx1;
    private javax.swing.JTextField cxo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
